### ISSUE TITLE
Logo Design For Font Renderer

### ISSUE THREAD

**Issue by zularizal** [rudifus/FontRenderer#1]
Hi @rudifus , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by rudifus** [comment]
Hi @zularizal, feel free to contribute. Looking forward to see it  :)

**Comment by zularizal** [comment]
Hi @rudifus  , this is the design logo for your project. I made three logo concepts. Which one do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/57352241-f585eb80-718e-11e9-95e5-61bd50277964.png)

**Comment by rudifus** [comment]
Cool,
I like the 1sr row the 1st icon -  possibly with dotted 'A' char  - what do you think?
[Dot Matrix](https://github.com/rudifus/FontRenderer/blob/master/generated/screens/DotMatrixNormal16px_1.webp)

**Comment by zularizal** [comment]
Hi @rudifus  I think this also looks good, but the dot will disappear when zooming out. Do you like it?

![bitmap](https://user-images.githubusercontent.com/38547278/57514021-c1026300-7339-11e9-8524-0f8b6795a189.png)
